// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int times=Integer.parseInt(args[0]);
		int c=0,more=0,less=0;
		while(c<times)
		{double num= Math.random();
			if(num>0.5)
				more+=1;
			else
				less+=1;
			c++;


		}System.out.println(more+"times that bigger then 0.5 and "+less+"times that smaller then 0.5");
	}
}
